### ISSUE TITLE
does not work for version 6.4.3?

### ISSUE THREAD

**Issue by filip-vt** [tenable/nessrest#60] opened 2015-10-05 09:32 UTC
Nessus version: 6.4.3 (#35) LINUX

I tried the following:

```
#!/usr/bin/env python

from nessrest import ness6rest

scan = ness6rest.Scanner(url="https://127.0.0.1:8834", login="LOGIN", password="PASSWORD", insecure=True)
scan.action(action="scans", method="get")
```

And I get the following result

```
*****************START ERROR*****************
JSON    :
{}
{}
HEADERS :
{'X-Cookie': 'token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'Content-type': 'application/json', 'Accept': 'text/plain'}
URL     : https://127.0.0.1:8834/scanners 
METHOD  : get
RESPONSE: 403


{
  "error": "You are not authorized to perform this request"
}
******************END ERROR******************
```

I use the same login/pass as to login to the UI btw. /scanners doesn't seem like the correct endpoint... But not sure though. Any ideas?

**Comment by filip-vt** [comment] 2015-10-05 10:13
I created a new user with Admin privileges and it seems to work now. So it was indeed a permissions issue...

**Comment by alexwebr** [comment] 2015-10-05 19:55
Thanks for following up. Glad to hear it works correctly. Closing.

**Closed by alexwebr** 2015-10-05 19:55 UTC

**Comment by rkrp** [comment] 2017-07-19 15:38
But, should one require admin privileges to even login through the API? So, is it by design that only admins are allowed to login through the API?

**Comment by Ar0xA** [comment] 2017-09-04 12:50
I agree with @rkrp API usage should not require admin privileges if we can create API keys for non-admins. This must be a bug
