### ISSUE TITLE
Issue with getting scan result

### ISSUE THREAD

**Issue by securisec** [tenable/nessrest#97] opened 2016-09-23 04:30 UTC
Hi, I am trying to run a simple scan, and then download the report in the nessus format. i am using scan_download(), but all i get back is the content of the policy itself. May i have some help on figuring this out please? i am trying to get the report in nessus format after the scan is completed.  Thanks in advance!

Here is the scan download piece of my script 

scanner.scan_add(targets="127.0.0.1")
scanner.scan_run()
file = open("/tmp/ness_faraday_Nessus.nessus", "w")
file.write(scanner.download_scan())
file.close()

here is a tiny sample of the output 

<item><pluginName>Good MDM Settings</pluginName>
<pluginId>66963</pluginId>
<fullName>Good MDM Settings[entry]:Port :</fullName>
<preferenceName>Port :</preferenceName>
<preferenceType>entry</preferenceType>
<preferenceValues></preferenceValues>
<selectedValue></selectedValue>
</item>

**Comment by streckc** [comment] 2016-09-23 21:33
What version of Nessus are you running against?
Is the sample output from the file that was created?

**Comment by securisec** [comment] 2016-09-23 21:35
Thanks for replying back to me. I am running the latest version of Nessus (downloaded two days ago). And yes, the sample is from the output file that is created. It looks like it is the policy/scan settings itself, and not the report of what was scanned.

**Comment by streckc** [comment] 2016-09-23 21:40
The .nessus format does have that information in it, but it appears that your output has lost the xml tags associated with it.  Example:

```
<item><pluginName>Good MDM Settings</pluginName>
<pluginId>66963</pluginId>
<fullName>Good MDM Settings[entry]:GMC Server :</fullName>
<preferenceName>GMC Server :</preferenceName>
<preferenceType>entry</preferenceType>
<preferenceValues></preferenceValues>
<selectedValue></selectedValue>
</item>
```

Not sure where you may have lost the tags.

**Comment by securisec** [comment] 2016-09-23 21:50
I am sorry, but I didnt paste my output properly. I do have those tags, but i must pasted incorrectly. here is another snippit of the same report. 

<item><pluginName>ADSI Settings</pluginName>
<pluginId>60024</pluginId>
<fullName>ADSI Settings[password]:Domain Password :</fullName>
<preferenceName>Domain Password :</preferenceName>
<preferenceType>password</preferenceType>
<preferenceValues></preferenceValues>
<selectedValue></selectedValue>
</item>
<item><pluginName>ADSI Settings</pluginName>
<pluginId>60024</pluginId>
<fullName>ADSI Settings[entry]:Domain Controller 2:</fullName>
<preferenceName>Domain Controller 2:</preferenceName>
<preferenceType>entry</preferenceType>
<preferenceValues></preferenceValues>
<selectedValue></selectedValue>
</item>
<item><pluginName>ADSI Settings</pluginName>
<pluginId>60024</pluginId>

As you can see, it is only information about what things are being scanned for, but not the scan report itself. Also, the file is written even before the scan is complete.

Would you be able to share your syntax/format you would use to download a .nessus report after a scan finishes?

**Comment by securisec** [comment] 2016-09-23 21:50
`<item><pluginName>ADSI Settings</pluginName>
<pluginId>60024</pluginId>
<fullName>ADSI Settings[password]:Domain Password :</fullName>
<preferenceName>Domain Password :</preferenceName>
<preferenceType>password</preferenceType>
<preferenceValues></preferenceValues>
<selectedValue></selectedValue>
</item>
<item><pluginName>ADSI Settings</pluginName>
<pluginId>60024</pluginId>
<fullName>ADSI Settings[entry]:Domain Controller 2:</fullName>
<preferenceName>Domain Controller 2:</preferenceName>
<preferenceType>entry</preferenceType>
<preferenceValues></preferenceValues>
<selectedValue></selectedValue>
</item>
<item><pluginName>ADSI Settings</pluginName>
<pluginId>60024</pluginId>
`

**Comment by streckc** [comment] 2016-09-25 15:41
What you are getting is the scan download in 'nessus' format.  This is an export/import format for transferring scan results between Tenable products.  If you go towards the end of the file, you will see the ReportItems in the XML that have the results.

If you are looking for a different format, then you will need to specify the format.  I believe the supported formats are 'nessus', 'html', 'csv', and 'db'.
 - 'nessus' - Import/Export format.
 - 'html' - HTML based report of the results.
 - 'csv' - Comma separated file with the results
 - 'db' - Database format that includes more information for transferring results.

I believe there may also be a 'pdf' format, but would have to confirm by looking at the api documentation on scan/download.

Example:

    scanner.download_scan(export_format="html")

Is this what you are looking for?

Thanks,
-chad

**Comment by securisec** [comment] 2016-09-25 16:58
Thanks again Chad for replying. Unfortunately, it fails to write the report to file no matter what format i am choosing. The format I would love to use is the XML format, which is why i am using the nessus format (set by default). Issue is that if i use the nessus format, it downloads the scan config, but not the scan results. If i use the html format, it write the first page of the report to file, but not the result... here is the exact piece of code i am using 

`scanner = ness6rest.Scanner(url="https://localhost:8834", login="login", password="password", insecure=True)

scanner.policy_set(name="scan_policy")
file = open("/tmp/nessus.html", "w")
scanner.scan_add(targets="127.0.0.1")
scanner.scan_run()
file.write(scanner.download_scan(export_format="html"))
file.close()`

**Comment by securisec** [comment] 2016-09-25 17:22
As an addition, I have also tried using the nessus_download_all.py script included here, and getting this error

`Traceback (most recent call last):
  File "./nessus_download_all.py", line 118, in <module>
    fp.write(scanner.download_scan(export_format=args.format))
TypeError: write() argument must be str, not bytes
`

**Comment by streckc** [comment] 2016-09-25 18:46
OK... I will give it a try and get back to you.  Thanks for the clarification.

**Comment by jimcarreer** [comment] 2016-09-25 19:09
@securisec 
The problem is the mode you're opening the file as, change this line:
`file = open("/tmp/nessus.html", "w")`
to
`file = open("/tmp/nessus.html", "wb")`
And try again.  The buffer you receive from download_scan is byte based, not a string.

**Comment by streckc** [comment] 2016-09-25 19:29
@jimcarreer That is what I found with nessus_download_all.py also, is to change the default mode to 'wb' vs 'wt' on line 112.

**Comment by jimcarreer** [comment] 2016-09-25 19:33
@streckc Yeah I think this might be python 3.x vs python 2.x they changed the string encoding to UTF so the "native" strings are no longer byte strings.

**Comment by jimcarreer** [comment] 2016-09-25 19:46
@securisec I'm not 100% sure, but as for your other issue: I believe you may be allowed to export partial results (the results of the scan thus far though it may not have been completed).  You probably need to poll the scan's status and only download the scan when it's status is no longer "running".  This is just a guess.

**Comment by securisec** [comment] 2016-09-25 19:48
Thanks @jimcarreer and @streckc, but the problem persists even with "wb". The file isnt written to disk before the scan is completed anymore, but it only downloads the report header, not the actual report. After "table of contents", the report is blank.

**Comment by securisec** [comment] 2016-09-25 19:49
same thing with nessus_download_all.py also

**Comment by jimcarreer** [comment] 2016-09-25 19:50
@securisec what version of nessus? And I guess were talking about the HTML export now? Not the .nessus export?

**Comment by securisec** [comment] 2016-09-25 19:53
I am on the latest version of nessus. What I really need is the .nessus report (in xml format) so that I can import it to some other programs, but for troubleshooting sake, I have been trying both .html and .nessus formats.

**Comment by jimcarreer** [comment] 2016-09-25 19:54
Try just the .nessus now with the "wb" on file open. I'd then compare the file written to the file you get when you go to Export > Nessus on the scan report page via the GUI.

**Comment by securisec** [comment] 2016-09-25 20:10
@jimcarreer When i download the report from the web gui, it is perfect, but an empty file with just headers when i try using the script.

**Comment by mokuso** [comment] 2017-01-21 03:58
Closing the file after write resolves the empty or partial file issue. Just add:
```fp.close```

**Closed** 2017-02-21 20:45 UTC
